### PR TITLE
fix: avoid deleting shared property

### PR DESCRIPTION
**Pull request by pedrobmarin**
@alangecker could you check if this is enough to cover #5 ?

### CODE REVIEW

**Comment by alangecker** [comment]
@pedrobmarin 
nope, still yields the same error.
It can't work because `const response = { ...body };` only recreates the topmost object and still adds the same child objects

**Comment by pedrobmarin** [comment]
Replaced with something similar to your suggestion

**Review by alangecker — APPROVED** [review]
now it works perfectly again! :) 🎉 

thanks for the work!

**Comment by pedrobmarin** [comment]
> PS: maybe additionally consider pushing the version number? :)

Sure! Is a release tag enough?

**Comment by alangecker** [comment]
> > PS: maybe additionally consider pushing the version number? :)
> 
> Sure! Is a release tag enough?

the version number in `package.json` should be incremented, otherwise npm on an existing setup would not know that the package got updated ;)

**Pull request merged**
